// <auto-generated />
namespace AutoTavex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class carVinRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(carVinRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202101040134143_carVinRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
